# Generated by Django 4.2.3 on 2023-07-23 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChefAmenagement',
            fields=[
                ('matriculeCA', models.AutoField(db_column='matriculeCA', primary_key=True, serialize=False)),
                ('nomCA', models.CharField(db_column='nomCA', max_length=100)),
                ('passwordCA', models.CharField(db_column='passwordCA', max_length=100)),
                ('roleCA', models.CharField(db_column='roleCA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChefIntervention',
            fields=[
                ('matriculeCI', models.AutoField(db_column='matriculeCI', primary_key=True, serialize=False)),
                ('nomCI', models.CharField(db_column='nomCI', max_length=100)),
                ('passwordCI', models.CharField(db_column='passwordCI', max_length=100)),
                ('roleCI', models.CharField(db_column='roleCI', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChefSupervision',
            fields=[
                ('matriculeCS', models.AutoField(db_column='matriculeCS', primary_key=True, serialize=False)),
                ('nomCS', models.CharField(db_column='nomCS', max_length=100)),
                ('passwordCS', models.CharField(db_column='passwordCS', max_length=100)),
                ('roleCS', models.CharField(db_column='roleCS', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('matriculeTechnicien', models.AutoField(db_column='matriculeTechnicien', primary_key=True, serialize=False)),
                ('nomTechnicien', models.CharField(db_column='nomTechnicien', max_length=100)),
                ('passwordTechnicien', models.CharField(db_column='passwordTechnicien', max_length=100)),
                ('roleTechnicien', models.CharField(db_column='roleTechnicien', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('codeEquipement', models.AutoField(db_column='codeEquipement', primary_key=True, serialize=False)),
                ('nomEquipement', models.CharField(db_column='nomEquipement', max_length=100)),
                ('site', models.CharField(db_column='site', max_length=100)),
                ('matRespoEntretien', models.ForeignKey(db_column='matriculeTechnicien', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_material.technicien')),
            ],
        ),
    ]
