# Generated by Django 4.2.3 on 2023-07-23 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportMaintenace',
            fields=[
                ('idRapport', models.AutoField(db_column='idRapport', primary_key=True, serialize=False)),
                ('libelle', models.CharField(db_column='libelle', max_length=100)),
                ('dateMaintenance', models.DateTimeField(db_column='dateMaintenance')),
                ('validite', models.BooleanField(db_column='validite', default=False)),
                ('codeEquipement', models.ForeignKey(db_column='codeEquipement', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_material.equipement')),
                ('matriculeTechnicien', models.ForeignKey(db_column='matriculeTechnicien', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_material.technicien')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeIntervention',
            fields=[
                ('idDemande', models.AutoField(db_column='idDemande', primary_key=True, serialize=False)),
                ('dateEmission', models.DateTimeField(db_column='dateEmission')),
                ('importance', models.CharField(db_column='importance', max_length=100)),
                ('codeAno', models.ForeignKey(db_column='codeAno', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_material.chefsupervision')),
                ('codeEquipement', models.ForeignKey(db_column='codeEquipement', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_material.equipement')),
                ('matriculeCI', models.ForeignKey(db_column='matriculeCI', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_material.chefintervention')),
            ],
        ),
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('codeCapteur', models.AutoField(db_column='codeCapteur', primary_key=True, serialize=False)),
                ('nomCapteur', models.CharField(db_column='nomCapteur', max_length=100)),
                ('typeCapteur', models.CharField(db_column='typeCapteur', max_length=100)),
                ('codeEquipement', models.ForeignKey(db_column='codeEquipement', on_delete=django.db.models.deletion.CASCADE, to='admin_material.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('codeAno', models.AutoField(db_column='codeAno', primary_key=True, serialize=False)),
                ('intitule', models.CharField(db_column='intitule', max_length=100)),
                ('gravite', models.CharField(db_column='gravite', max_length=100)),
                ('matriculeCS', models.ForeignKey(db_column='matriculeCS', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_material.chefsupervision')),
            ],
        ),
    ]
